### ISSUE TITLE
*** Test Issue *** used for testing HDE

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#1]
**This is the 1st test issue for testing HDE website.**

Rewards are here for testing purposes and won't be paid.

**Comment by favirnho** [comment]
This is the 1st test issue for testing HDE website.

Rewards are here for testing purposes and won't be paid

**Comment by Romashka907** [comment]
Rewards are here for testing purposes and won't be paid
