### ISSUE TITLE
Create a video about stZEN

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#10]
**Goals:** 
- Create a short video highlighting what stZEN is and the uses of our new ERC-20 token
- Share the video on your preferred platform 

**Scope of work:** 

You must create an in-depth video (no less than 5 minutes) about stZEN for beginners
The video can be in any of the following styles:

- Token review style
- Explainer style
- Tutorial style

The video must include the following content: 
- What is stZEN
- Relations and differences between ZEN and stZEN
- How to get stZEN
- What you can do with stZEN

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. This task should be completed within 4 weeks. If a user does not complete this task within the allotted time, it will be considered open for another user to complete. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the video before approval.

Ambassadors that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $200 (Paid in ZEN)**

**Comment by Andrzej0xa0** [comment]
I have completed the task :-)

here is the link to the video https://youtu.be/TLGSkWt4U-s

**Comment by Horusfeathers** [comment]
> I have completed the task :-)
> 
> here is the link to the video https://youtu.be/TLGSkWt4U-s

The task meets all requirements and has been approved by marketing @PowerVANO

**Comment by PowerVANO** [comment]
Thank you for your work @Andrzej0xa0 and for your approval @Horusfeathers! Issue is closed. Submitting for the payment processing.
