### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - Korean

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#12]
**Scope of work:** 

This task is to translate the following pages in Korean
- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened. 

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by Horusfeathers** [comment]
This task has been accepted and nearly completed by Jonghun.

**Comment by tiago11h** [comment]
acepto traducir todo

**Comment by Horusfeathers** [comment]
> acepto traducir todo

This task can only be completed by a Horizen ambassador. You can apply for the program at https://www.horizen.io/ambassadors/

**Comment by Horusfeathers** [comment]
This task has been picked up by @nobleminsu.

**Comment by nobleminsu** [comment]
@Horusfeathers Should I register for the Horizen ambassador program?

**Comment by nobleminsu** [comment]
Hello, I've finished the home page translation. Please check.

**Comment by PowerVANO** [comment]
@Horusfeathers Can you please confirm the completion of the task?

**Comment by Horusfeathers** [comment]
@PowerVANO - Task is pending review.

**Comment by Horusfeathers** [comment]
@PowerVANO the translations have been approved. @nobleminsu may complete the bounty claim form.

**Comment by PowerVANO** [comment]
@nobleminsu Please log in your HDE profile and submit the bounty claim form (button towards the end of the page): https://hde.horizen.io/account

**Comment by PowerVANO** [comment]
Bounty has been paid. Issue closed.
