### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - Korean

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#13]
**Scope of work:** 

- Translate the full Zendoo whitepaper in Korean: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened. 

**Budget: $200 (Paid in ZEN)**

**Comment by bilall7** [comment]
CAN I TAKE THIS TASK

**Comment by bilall7** [comment]
CAN I TAKE THIS TASK

**Comment by Zeus-5** [comment]
Can i please do this task?

**Comment by PowerVANO** [comment]
@bilall7 @Zeus-5 yes, but you need to first apply and get approved for our Ambassadors program: https://www.horizen.io/ambassadors/

**Comment by bilall7** [comment]
I already send app

Le mer. 14 juil. 2021 à 11:13, PowerVANO ***@***.***> a
écrit :

**Comment by Horusfeathers** [comment]
This task has been taken by @nobleminsu, who will submit the documentation within the required timeframe.

**Comment by tiago11h** [comment]
Ya lo traducí

**Comment by Horusfeathers** [comment]
> Ya lo traducí

You must be part of the ambassador program and approved prior to accepting this task to be eligible. @nobleminsu is currently approved and working on this task.

**Comment by cmb11011995** [comment]
Please approve me for ambassador program and assign this task as well as task translating to Russian: I can finish the white paper transalations in 2 days time.

**Comment by Horusfeathers** [comment]
@cmb11011995 - The Korean translation task has already been accepted by another member. Please apply to the ambassador program to be considered for the Russian translation tasks.

**Comment by cmb11011995** [comment]
I have applied. Many times. 😂

**Comment by cmb11011995** [comment]
I have . Several times in fact… I have never heard anything back. At this point I’m just going to start translating it. If I can’t be approved to be an ambassador I’ll just pitch it. If you’re able to find my application and approve it please let me know.

**Comment by Undertakergabo** [comment]
Puedo tomar está tarea
