### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - Russian

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#14]
**Scope of work:** 

This task is to translate the following pages in Russian
- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

Original English texts for translation:
Homepage: https://docs.google.com/document/d/116XuA8qVC6uOAKwGSEc4uCgieJKMd1neQyjVmGXO3pw/edit?usp=sharing
Sidechain Page: https://docs.google.com/document/d/1CdFDrqHeJhod68TkWJPW4ccdnGur7w0JLO3eIffRDKA/edit?usp=sharing
Nodes Page: https://docs.google.com/document/d/1CdFDrqHeJhod68TkWJPW4ccdnGur7w0JLO3eIffRDKA/edit?usp=sharing

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened. 

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by Albhion** [comment]
Hey! Can I take this task? Let me Know and Can I use some translator apps ?

**Comment by PowerVANO** [comment]
Hey @Albhion 

You can take the task but before that, please visit Ambassador program page to review it https://www.horizen.io/ambassadors/ and [apply here](https://forms.gle/XdpNYXKgsAhdnP8m7). Task is for Ambassadors only.

Once approved, you can start working on the task.

Also, using translator apps is discouraged as the overall quality of the work is not great when using such apps. Your work is subject to review and it might get rejected if the translation is low quality.
