### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - Russian

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#15]
**Scope of work:** 

- Translate the full Zendoo whitepaper in Russian: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened. 

**Budget: $200 (Paid in ZEN)**

**Comment by rubruno** [comment]
@PowerVANO Hi! Ok, it's very simple, i'm ready!

**Comment by PowerVANO** [comment]
Hey @rubruno 
We need to onboard you as an ambassador first.
Please contact our Communications Manager, Erica Hamilton on Discord: Horusfeathers#0323 or at email: erica [at] horizen.io.

**Comment by Emad980** [comment]
>**WORK FIELD:** > >* Full white Zendoo paper translation in Russian: https://www.horizon.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf >> **Milestones Scheduling:** >* Can't complete this task. A person who accepts this task must provide a status update once a week. If the person accepting this task does not complete the main events of the above table, the task will reopen. >> **Budget: $200 (paid at ZEN)** I'm ready

**Comment by Emad980** [comment]
I am ready 

> 
[Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol (1).pdf](https://github.com/HorizenOfficial/HDE-Proposals/files/6402835/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.1.pdf)

**Comment by Emad980** [comment]
It's simple

**Comment by PowerVANO** [comment]
Hi @Emad980 

Please apply to become an [ambassador](https://www.horizen.io/ambassadors/) first: https://forms.gle/XdpNYXKgsAhdnP8m7

The task is currently restricted to Ambassadors only.

**Comment by myphuong776** [comment]
ok

**Comment by arfasobiz** [comment]
@PowerVANO can I start ??

**Comment by Horusfeathers** [comment]
> @PowerVANO can I start ??

Hi @arfasobiz. This task is only available to Horizen ambassadors at this time.

**Comment by arfasobiz** [comment]
I registered. 
whether anyone from my area has registered. 
? 
I only saw that there were only 4 people who registered

**Comment by arfasobiz** [comment]
I prefer to beg for work because I really need it.
a little money to eat and go to school for my children. I am struggling
economically because I lost my job in the factory
and my children need school.
I only need no more than 500 dollars or a few zen coins.
thank you for the response
ZEN: znhU1D8mqmEUEQ6LmaSAn4cPMEPSbrodfDL
stZEN: 0x74CcF12E7aC5ebA5231AfB16B5a620947DC9308f


Pada tanggal Min, 2 Mei 2021 21:45, Erica ***@***.***>
menulis:

**Comment by dimpz18** [comment]
@PowerVANO  Can i apply as ambassador to start the task and how to be ambassador?

**Comment by PowerVANO** [comment]
> @PowerVANO Can i apply as ambassador to start the task and how to be ambassador?

Of course @dimpz18! Please visit Ambassador program page to review it https://www.horizen.io/ambassadors/ and [apply here](https://forms.gle/XdpNYXKgsAhdnP8m7).

Once approved, you can start working on the task.

**Comment by dimpz18** [comment]
I already applied. Hope you can choose me to become one of your ambassador. Thank you..

Sent from Yahoo Mail on Android 
 
  On Thu, May 13, 2021 at 4:36 PM, ***@***.***> wrote:   



@PowerVANO Can i apply as ambassador to start the task and how to be ambassador?


Of course @dimpz18! Please visit Ambassador program page to review it https://www.horizen.io/ambassadors/ and apply here.

Once approved, you can start working on the task.

**Comment by cmb11011995** [comment]
Applied for ambassador. How long should it take to get a response?
