### ISSUE TITLE
Ambassador Task: Create a video about stZEN - English

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#21]
**Goals:** 

- Create a short video highlighting what stZEN is and the uses of our new ERC-20 token
- Share the video on your preferred platform 
- This video must be in English, subtitles in other languages are accepted

**Scope of work:** 

You must create an in-depth video (no less than 5 minutes) about stZEN for beginners. This video must be in English.

The video can be in any of the following styles:

- Token review style
- Explainer style
- Tutorial style

The video must include the following content: 
- What is stZEN
- Relations and differences between ZEN and stZEN
- How to get stZEN
- What you can do with stZEN

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. This task should be completed within 4 weeks. If a user does not complete this task within the allotted time it will be considered open for another user to complete. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the video before approval. 

Ambassadors that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $200 (Paid in ZEN)**

**Comment by nomiikt** [comment]
Hey I am interested in this project can I take this task?

**Comment by PowerVANO** [comment]
Hi @nomiikt, sure!
But you first have to apply and get approved as a Horizen Ambassador: https://www.horizen.io/ambassadors/

**Comment by HaulMAD** [comment]
@PowerVANO I applied to be a ambassador at https://www.horizen.io/ambassadors/ how long will it take to get a update on the application?

**Comment by HaulMAD** [comment]
I think I’m in I would like to take the task

**Comment by PowerVANO** [comment]
@HaulMAD The review process typically takes around 1-2 days.

**Comment by GuiltyWaiver** [comment]
I would LOVE to do a video about this. I run a channel on YouTube myself and a solid instagram with quite a lot of followers.  I'm new here and would love to be in board with this

**Comment by PowerVANO** [comment]
> I would LOVE to do a video about this. I run a channel on YouTube myself and a solid instagram with quite a lot of followers. I'm new here and would love to be on board with this

Please reply for our Ambassador program first: https://www.horizen.io/ambassadors

**Comment by GuiltyWaiver** [comment]
Did I got denied lol

**Comment by GuiltyWaiver** [comment]
I have a decent follower base between instagram twitch and YouTube too like
close to 700
