### ISSUE TITLE
Ambassador Task: Write a technical article or blog about building on the Horizen ecosystem

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#22]
**Goals:** 

- Create an article or blog of any length describing what you would like to build on Horizen or describing how to build on the Horizen ecosystem. 
- Share the article on your preferred platform.

**Scope of work:** 

This article can be any length but must cover at least one thing you would like to build on the Horizen ecosystem. 

**Schedule Milestones:** 

This task may only be completed by an **official Horizen Ambassador**. This task should be completed within 4 weeks of accepting the task. If a user does not complete this task within the allotted time, it will be considered open for another user to complete. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval. 

Ambassadors that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $50 per completed article, $200 in total (Paid in ZEN)**

(4 spots left)

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO, could I take this task? please.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag I think yes, but tagging @Horusfeathers for confirmation to check if anyone has taken it or not.

**Comment by Horusfeathers** [comment]
> Hey @PowerVANO, could I take this task? please.

This task is still available and @luisantoniocrag is eligible.

**Comment by xgarreau** [comment]
Hi ! 

Would this article be eligible for this task ?
--> https://mescryptos.fr/une-application-de-sidechain-horizen-le-bridge/

Best regards,
Xavier

**Comment by Horusfeathers** [comment]
Yes @xgarreau. This article is eligible. Please submit a bounty claim form.

**Comment by xgarreau** [comment]
> Yes @xgarreau. This article is eligible. Please submit a bounty claim form.

Thank you. I just claimed it with PR #49 

Have a nice day.
Xavier

**Comment by DeFiMoney-Printer** [comment]
@PowerVANO does the tag bounty_paid_2 mean there is 2 slots of 4 remain? thanks!

**Comment by PowerVANO** [comment]
@DeFiMoney-Printer yes, that is correct. HDE website picks up payments using those labels. 2 spots left here.

**Comment by Sam-Steel55** [comment]
Published my article @Horusfeathers 

https://link.medium.com/hKYSCIKQOrb

**Comment by Horusfeathers** [comment]
> Published my article @Horusfeathers
> 
> https://link.medium.com/hKYSCIKQOrb

Well written! Please submit your bounty claim request.

**Comment by Sam-Steel55** [comment]
> > Published my article @Horusfeathers
> > https://link.medium.com/hKYSCIKQOrb
> 
> Well written! Please submit your bounty claim request.

Thank you Erica. Claim has been submitted @PowerVANO

**Comment by PowerVANO** [comment]
@Sam-Steel55 Claim approved, submitted for payment.

**Comment by paragismb** [comment]
Can I take up this task? Gonna write an article.

**Comment by Horusfeathers** [comment]
> 

Yes you may!

**Comment by Horusfeathers** [comment]
> Can I take up this task? Gonna write an article.

Yes you may!

**Comment by PowerVANO** [comment]
@Sam-Steel55 your payment has been sent for this task. Thanks for your work!

**Comment by paragismb** [comment]
> > Can I take up this task? Gonna write an article.
> 
> Yes you may!

Ok. Starting work.

**Comment by paragismb** [comment]
Work done. 
Article: https://thecoinbuzz.substack.com/p/building-a-supply-chain-management
Tweet: https://twitter.com/paragism_/status/1554522318978039813?s=20&t=Zpddm7XGUgV9fq3zNAAXug

**Comment by Horusfeathers** [comment]
> Work done. Article: https://thecoinbuzz.substack.com/p/building-a-supply-chain-management Tweet: https://twitter.com/paragism_/status/1554522318978039813?s=20&t=Zpddm7XGUgV9fq3zNAAXug

This piece is approved. Please submit your bounty claim form. 

@PowerVANO

**Comment by PowerVANO** [comment]
Payment in progress.

**Comment by PowerVANO** [comment]
@paragismb @Horusfeathers Payment has been made. Closing this task.
