### ISSUE TITLE
Ambassador Task: Create a video about use cases that can be built on Zendoo

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#23]
**Goals:** 

- Create a video highlighting what use cases can benefit from building on Zendoo and why Horizen is better than competing platforms
- Share the video on your preferred platform 

**Scope of work:** 

The video can be in any of the following styles:

- Platform review style
- Explainer style

The video must include the following content: 

- What is Zendoo
- At least 1 use case that could benefit from building on Zendoo
- Why the use case(s) benefit from build on Zendoo vs competitors

**Schedule Milestones:** 

This task may only be completed by an official Horizen Ambassador. This task should be completed within 4 weeks of accepting the task. If a user does not complete this task within the allotted time, it will be considered open for another user to complete. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the video before approval. 

Ambassadors that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $100 (Paid in ZEN)**

**Comment by cryptoclarity** [comment]
just applied to be an ambassador. Will be great to do a video on this.

**Comment by DeFiMoney-Printer** [comment]
@PowerVANO the task is still available?

**Comment by PowerVANO** [comment]
@DeFiMoney-Printer sorry for the late reply here.

Let's wait for @horusfeathers to check the status of this task.

**Comment by Horusfeathers** [comment]
This task is complete. @PowerVANO please close put the task
