### ISSUE TITLE
Ambassador Task: Write and publish an article about Horizen

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#24]
**Scope of work:** 

- Write an article about Horizen
- Should include what Horizen is, why you like Horizen, and mention that sidechains are coming to mainchain soon. 
- Must publish on blog or news platform of your choice (Medium, personal blog, etc.)

**Scheduled Milestones:**

This task may only be completed by an official Horizen Ambassador. This task is available to the first 3 ambassadors that complete the task successfully. For the task to be considered complete, the article will need to be reviewed and approved by the Horizen team. The team may request edits to the article before approval. 

Ambassadors that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $50 per completed article, $150 in total (Paid in ZEN)**

**Comment by Horusfeathers** [comment]
This task has been completed by luisantoniocrag. The bounty claim form should be submitted soon.

**Comment by luisantoniocrag** [comment]
Submitted! Thank you.

**Comment by PowerVANO** [comment]
> Submitted! Thank you.

Payment is being processed.

**Comment by Sylver-blade** [comment]
Article done in french since so many years ... Don't know how it work to submit ... 

https://fredericstlaurent.com/2021/01/10/417/

**Comment by Sylver-blade** [comment]
I think I'm too late anyway I'm not an ambassador just made my demand

**Comment by PowerVANO** [comment]
@Sylver-blade Thanks! Please apply for Ambassadors' program here: https://www.horizen.io/ambassadors/ and @Horusfeathers will help with the article review and ambassador application.

**Comment by Horusfeathers** [comment]
> Published my article ZENvangelist Journal - Building a new world one ZEN at a time! https://www.publish0x.com/mind-puzzle/zenvangelist-journal-building-a-new-world-one-zen-at-a-time-xlzqpny?a=pmbk1p5ezJ

Submission approved! Thanks.

**Comment by PowerVANO** [comment]
> Published my article ZENvangelist Journal - Building a new world one ZEN at a time! https://www.publish0x.com/mind-puzzle/zenvangelist-journal-building-a-new-world-one-zen-at-a-time-xlzqpny?a=pmbk1p5ezJ

Payment is being processed.

**Comment by PowerVANO** [comment]
This has been paid already.

**Comment by pvmihalache** [comment]
@PowerVANO can I write again if this is still open?

**Comment by Horusfeathers** [comment]
> @PowerVANO can I write again if this is still open?

Yes you can!

**Comment by DeFiMoney-Printer** [comment]
@PowerVANO let me know if this is still open. thanks!

**Comment by DeFiMoney-Printer** [comment]
@Horusfeathers has the final submission been granted?

**Comment by paragismb** [comment]
Can I take up this task?

**Comment by paragismb** [comment]
As discussed with Erica, started working on this.

**Comment by paragismb** [comment]
Work is done. 
Article: https://thecoinbuzz.substack.com/p/the-future-is-being-built-on-horizen
Tweet: https://twitter.com/paragism_/status/1548713518001975296?s=20&t=tDqokY1f8AawSKJ2RjNNWA

**Comment by Horusfeathers** [comment]
This is accepted. Thank you. Please submit a claim form. 

@PowerVANO please close out the task

**Comment by PowerVANO** [comment]
Payment is being processed.

**Comment by PowerVANO** [comment]
Payment has been done. @paragismb Thank you very much for your work!
