### ISSUE TITLE
Ambassador Task: Write a walkthrough article or blog about how to create a blockchain on Zendoo testnet

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#27]
**Goals:** 

- Create an article or blog of any length walking through the process of building on Zendoo testnet 
- Share the article on your preferred platform 

**Scope of work:** 

- This article can be any length but must cover:
- How to get test ZEN
- Where to download the SDK
- Where to find documentation and resources
- The steps required to build a blockchain
- Technical requirements for building a blockchain on Zendoo
- What is Zendoo

**Schedule Milestones:** 

This task may only be completed by an official Horizen Ambassador or pre approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval. 

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide bi-weekly updates during the period they are working on the task. 

**Budget: $300 (Paid in ZEN)**

**Comment by lazzari09** [comment]
Can I begin this task and submit?

**Comment by SiongokBrian** [comment]
Is this task still available? I'm a blogger.

**Comment by PowerVANO** [comment]
Hi @lazzari09 & @SiongokBrian 

You should apply for our Ambassadors' program first: https://www.horizen.io/ambassadors/

**Comment by Dav1dKillz** [comment]
> **Goals:** 
> 
> - Create an article or blog of any length walking through the process of building on Zendoo testnet 
> - Share the article on your preferred platform 
> 
> **Scope of work:** 
> 
> - This article can be any length but must cover:
> - How to get test ZEN
> - Where to download the SDK
> - Where to find documentation and resources
> - The steps required to build a blockchain
> - Technical requirements for building a blockchain on Zendoo
> - What is Zendoo
> 
> **Schedule Milestones:** 
> 
> This task may only be completed by an official Horizen Ambassador or pre approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval. 
> 
> If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io
> 
> Ambassadors that accept this task must provide bi-weekly updates during the period they are working on the task. 
> 
> **Budget: $300 (Paid in ZEN)**
>

**Comment by Sam-Steel55** [comment]
I would like to complete this task.

**Comment by Sam-Steel55** [comment]
I've completed and published my article :

 https://link.medium.com/rzEyIMlMSqb

**Comment by Sam-Steel55** [comment]
> **Goals:**
> 
> * Create an article or blog of any length walking through the process of building on Zendoo testnet
> * Share the article on your preferred platform
> 
> **Scope of work:**
> 
> * This article can be any length but must cover:
> * How to get test ZEN
> * Where to download the SDK
> * Where to find documentation and resources
> * The steps required to build a blockchain
> * Technical requirements for building a blockchain on Zendoo
> * What is Zendoo
> 
> **Schedule Milestones:**
> 
> This task may only be completed by an official Horizen Ambassador or pre approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval.
> 
> If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io
> 
> Ambassadors that accept this task must provide bi-weekly updates during the period they are working on the task.
> 
> **Budget: $300 (Paid in ZEN)**

I've completed and published my article :

https://link.medium.com/rzEyIMlMSqb

**Comment by Sam-Steel55** [comment]
I've completed and published my article :

https://link.medium.com/rzEyIMlMSqb

**Comment by PowerVANO** [comment]
Payment processing for this task.

**Comment by Sam-Steel55** [comment]
> Payment processing for this task.

Received. Thanks
