### ISSUE TITLE
Ambassador Task: Create a video tutorial on how to build a sidechain on Zendoo

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#28]
**Goals:** 

- Create a video highlighting what use cases can benefit from building on Zendoo and why Horizen is better than competing platforms
- Share the video on your preferred platform 

**Scope of work:** 

- The video must include the following content: 
- How to get test ZEN
- Where to download the SDK
- Where to find documentation and resources
- The steps required to build a blockchain
- Technical requirements for building a blockchain on Zendoo
- What is Zendoo

**Schedule Milestones:** 

This task may only be completed by an official Horizen Ambassador or pre approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval. 

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide bi-weekly updates during the period they are working on the task. 

**Budget: $300 (Paid in ZEN)**

**Comment by JdevStudios** [comment]
I would like to get this issue/bounty assigned

**Comment by PowerVANO** [comment]
@JdevStudios If you are already a Horizen Ambassador, please wait for @horusfeathers confirmation and you can go forward with it.
Otherwise, please apply to our Ambassador program first: https://www.horizen.io/ambassadors/

**Comment by Horusfeathers** [comment]
@JdevStudios - Because you are not an ambassador at this time, please contact me via email at erica@horizen.io and we can review your credentials to complete this task. Thanks!
