### ISSUE TITLE
Ambassador Task: Translate the Darlin Whitepaper - French

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#29]
**Scope of work:**

- Translate the full the Darlin whitepaper into French: https://www.horizen.io/assets/files/Darlin-A-Proof-Carrying-Data-Scheme-Based-on-Marlin-Whitepaper.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by EmboyG** [comment]
[Darlin-A-Proof-Carrying-Data-Scheme-Based-on-Marlin-Whitepaper.it.fr.pdf](https://github.com/HorizenOfficial/HDE-Proposals/files/7576244/Darlin-A-Proof-Carrying-Data-Scheme-Based-on-Marlin-Whitepaper.it.fr.pdf)

**Comment by EmboyG** [comment]
Done whitepaper translate please send me an email how to claim the paid task at iamnamba4@gmail.com

**Comment by Horlah1** [comment]
Can I be involved in this project

**Comment by PowerVANO** [comment]
Hi @EmboyG and @Horlah1 

You should apply for our Ambassadors' program first: https://www.horizen.io/ambassadors/
