### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - French

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#30]
**Scope of work:**

This task is to translate the following pages into French

- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by EmboyG** [comment]
[Darlin-A-Proof-Carrying-Data-Scheme-Based-on-Marlin-Whitepaper.it.fr.pdf](https://github.com/HorizenOfficial/HDE-Proposals/files/7576271/Darlin-A-Proof-Carrying-Data-Scheme-Based-on-Marlin-Whitepaper.it.fr.pdf)


Please see details.  Info about claiming my paid task

**Comment by TechnoHorizen** [comment]
Ill take some pages in the Horizen.io website

**Comment by PowerVANO** [comment]
Hi @EmboyG @TechnoHorizen 
Are you Horizen Ambassadors already? If not, please apply here first: https://www.horizen.io/ambassadors/

**Comment by Kolush1** [comment]
Hi, is this task still open ? If yes, I may apply for Horizen Ambassadors program.
