### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - Italian

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#36]
**Scope of work:**

- Translate the full Zendoo whitepaper in Italian: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by toprakdere** [comment]
i want to translate

**Comment by SolomonViktor** [comment]
I too want to translate

**Comment by PowerVANO** [comment]
@toprakdere @SolomonViktor 
Are you Horizen Ambassadors? If not, please apply first here, before starting your work: https://www.horizen.io/ambassadors/

**Comment by bettira07** [comment]
نعم اريد ان اعمل اعلمني مافعل

**Comment by saddam7740** [comment]
اريد ان اترجم

**Comment by yzydbdhmhsnsyd** [comment]
اريد ان اترجم

**Comment by ranaezzelarab** [comment]
I'm ready

**Comment by 773937434** [comment]
How i get this task
