### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - German

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#37]
**Scope of work:**

This task is to translate the following pages into German 

- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by TianahEtokh1** [comment]
I am interested

**Comment by TianahEtokh1** [comment]
I am Interested and I am already an Ambassador Sir.

**Comment by PowerVANO** [comment]
@horusfeathers Can you please confirm if this task is still available?

**Comment by Horusfeathers** [comment]
@TianahEtokh1 you may proceed with the task
