### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - German

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#38]
**Scope of work:**

- Translate the full Zendoo whitepaper in Italian: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by TianahEtokh1** [comment]
I am interested in this task

**Comment by iszyeffiong** [comment]
I am interested in the task

**Comment by vanhien86** [comment]
tôi quan tâm đến nhiệm vụ này

**Comment by Nicolas080808** [comment]
Je suis intéressé svp pour faire le task . Comment faire svp
