### ISSUE TITLE
Ambassador Task: Translate the Horizen Whitepaper - German

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#39]
**Scope of work:**

- Translate the full Zendoo whitepaper in German: https://www.horizen.io/assets/files/Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by oMurmeltiero** [comment]
@PowerVANO Hi can i translate it in german?

**Comment by oMurmeltiero** [comment]
[Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf](https://github.com/HorizenOfficial/HDE-Proposals/files/7775672/Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf)

Start: Page 1 translated.

**Comment by PowerVANO** [comment]
Hi @oMurmeltiero 
Are you the Horizen Ambassador already? If not, please apply and wait for the approval before working on this task: https://www.horizen.io/ambassadors/

**Comment by Dannyednut** [comment]
Hi I can translate in German

**Comment by PowerVANO** [comment]
@Dannyednut 

Are you Horizen Ambassador already? If not, please apply first and wait for the approval before starting this task: https://www.horizen.io/ambassadors/

**Comment by bettira07** [comment]
نعم جاهز
