### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - Spanish

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#40]
**Scope of work:**

This task is to translate the following pages into Spanish

- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by CIELO1705** [comment]
Hi PowrVANO, I am interested in translating in Spanish, how do I get them to take me into account. since I am not an ambassador.


hola PowrVANO, Estoy interesada para traducir en español, como hago para que me tomen encuenta. ya que no soy embajadora.

**Comment by PowerVANO** [comment]
Hi @CIELO1705 
Please apply for the Ambassador program here: https://www.horizen.io/ambassadors/

**Comment by Varshans2** [comment]
boss I HAVE DID ALL THESE TRANSLATIONS 

not accepted as a ambasadors

**Comment by FranChiscu** [comment]
Hi, i take the task :)

**Comment by FranChiscu** [comment]
Hi @Horusfeathers can i take the task? It is aviable?

**Comment by PowerVANO** [comment]
@FranChiscu let's wait for @horusfeathers to check status. She will be back in office next week.

**Comment by FranChiscu** [comment]
Okey, i wait their response. 
Thanks

**Comment by Horusfeathers** [comment]
This task is completed previously. Thank you. @PowerVANO please close the task
