### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - Spanish

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#41]
**Scope of work:**

- Translate the full Zendoo whitepaper in Spanish: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by CIELO1705** [comment]
hola estoy dispuesta a trabajer en la traducion del documento. estoy  atenta a su respuesta gracias

**Comment by PowerVANO** [comment]
@CIELO1705 @sangambeh03 
Please apply for and wait for the approval for the Ambassadors' program first: https://www.horizen.io/ambassadors/

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO @Horusfeathers can I take this task?

**Comment by Horusfeathers** [comment]
> Hey @PowerVANO @Horusfeathers can I take this task?

Yes you may!

**Comment by Varshans2** [comment]
i have done it already[]
[Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol (1).pdf](https://github.com/HorizenOfficial/HDE-Proposals/files/8208058/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.1.pdf)
(

**Comment by PowerVANO** [comment]
Hi @Varshans2 
These tasks are limited to Horizen Ambassadors. Please apply for the program first.

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO,@Horusfeathers, sorry for the long delay. Now I'm back from my big rest LoL. May I still take this task? I hope to finish it next week.

**Comment by deztas1** [comment]
Hola @Varshans2 , puedo hacer esta tarea?

**Comment by Horusfeathers** [comment]
> Hi @PowerVANO,@Horusfeathers, sorry for the long delay. Now I'm back from my big rest LoL. May I still take this task? I hope to finish it next week.

Yes, you may take this task.

**Comment by FranChiscu** [comment]
hii, i can do it this task? i'm a native spanish. i can do it in 1 week if do you prefer, 
thanks.

**Comment by FranChiscu** [comment]
Yes.

**Comment by Horusfeathers** [comment]
This task is still pending @luisantoniocrag and not available at this time.

**Comment by FranChiscu** [comment]
Okey, will you notify me by email?
Thanks

**Comment by FranChiscu** [comment]
Yes i know, i wait for the respone of luisantonio

**Comment by FranChiscu** [comment]
Do you have another pending task of translate to spanish?

**Comment by luisantoniocrag** [comment]
Hi @FranChiscu I'm in review-stage. I think that #40 is available for work?

**Comment by FranChiscu** [comment]
Okey, i take the task for me. Thanks.
When i finish to translate where do i send it?

**Comment by luisantoniocrag** [comment]
You should ask in #40 and tag Horusfeathers

**Comment by FranChiscu** [comment]
Okey, thanks

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO @Horusfeathers.

There is the Zendoo Whitepaper translated (Spanish):
https://docs.google.com/document/d/1jZquOcFB30oMZyGrIHDGIP_yUc6mjKrnLnvBpQBN1vI/edit?usp=sharing

Please let me know any changes if it needs.

**Comment by Horusfeathers** [comment]
> Hi @PowerVANO @Horusfeathers.
> 
> There is the Zendoo Whitepaper translated (Spanish): https://docs.google.com/document/d/1jZquOcFB30oMZyGrIHDGIP_yUc6mjKrnLnvBpQBN1vI/edit?usp=sharing
> 
> Please let me know any changes if it needs.

Thank you. Please submit your claim form.

**Comment by luisantoniocrag** [comment]
awesome! just submitted!

**Comment by PowerVANO** [comment]
Payment is being processed.

**Comment by PowerVANO** [comment]
@luisantoniocrag payment has been made. Thank you for your work!
