### ISSUE TITLE
Ambassador Task: Translate the Horizen Whitepaper - Spanish

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#42]
**Scope of work:**

- Translate the full Zendoo whitepaper in Spanish: https://www.horizen.io/assets/files/Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO,

Can I take this task? I disconnected a bit from the crypto world hehe, but I'm getting back to it.

I know I have another pending task, but for now, I know I can handle this since my mother tongue is Spanish and I have translated many research papers and whitepapers.

**Comment by CIELO1705** [comment]
hola estoy interesada en trabajar con uds traduciendo documentos. gracias le agradeceria que me pudieran tomar encuenta

**Comment by CIELO1705** [comment]
hola mi correo es nadezkharomero@gmail.com

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 
I think you can! @horusfeathers Can you please confirm?

@CIELO1705 Please apply for the Horizen Ambassador program first before taking any tasks: https://www.horizen.io/ambassadors/

**Comment by luisantoniocrag** [comment]
This is the doc that I am working the translation: https://docs.google.com/document/d/1dYjphP8YG4Ua0DZyzzLFkh5MYAq7q8wj0fJJ7bnYxw4/edit?usp=sharing

I will notify you when finished. I just need to do proofreading.

**Comment by Horusfeathers** [comment]
> Hey @luisantoniocrag I think you can! @Horusfeathers Can you please confirm?
> 
> @CIELO1705 Please apply for the Horizen Ambassador program first before taking any tasks: https://www.horizen.io/ambassadors/

That's correct. @luisantoniocrag is eligible.

**Comment by Mobylizer** [comment]
Is anyone working on this at the moment.  I'm fluent in Spanish. I lived in Mexico for good time and had to interact with the people and I learned it  within 6 months. I'm also quite proficient in English and I understand the phrasing in Spanish and often multiple ways of wording the same phrase, and the same for English to Spanish. If no one is working on this I would like to take a crack at it. If someone is currently working on it, then I won't try to start and present you with a demo of what I can do and in the time frame of 4 weeks, if not sooner. mobylizer@gmail.com lemme know what's up.

**Comment by PowerVANO** [comment]
Hi @Mobylizer thanks for your wish to contribute but I think @luisantoniocrag is working on this.

@luisantoniocrag can you please update regarding the progress?

**Comment by Mobylizer** [comment]
Darn, well thanks for letting me know. I'll try to check in regularly and
check out if there are any tasks available that I know I am able to
accomplish. I'd love to be of some use and help in some way in the future.
=) Have a great weekend!

Mobylizer

**Comment by luisantoniocrag** [comment]
@PowerVANO I just need to do proofreading on the last 4 pages: https://docs.google.com/document/d/1dYjphP8YG4Ua0DZyzzLFkh5MYAq7q8wj0fJJ7bnYxw4/edit?usp=sharing

**Comment by PowerVANO** [comment]
Thanks @luisantoniocrag!

And you are welcome @Mobylizer, we will be happy to see you again!

**Comment by Philanthropist517** [comment]
This is interesting

**Comment by Undertakergabo** [comment]
Holaaa me gustaría tomar esa tarea los haría muchos gustos

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO! Sorry for the delay.

I just completed the Spanish translation: https://docs.google.com/document/d/1dYjphP8YG4Ua0DZyzzLFkh5MYAq7q8wj0fJJ7bnYxw4/edit?usp=sharing

What are the next steps?

**Comment by Undertakergabo** [comment]
No veo ni error en la traducción

**Comment by Undertakergabo** [comment]
https://us.docs.wps.com/l/sAEnpbAK9p5ubAZrWkfarpxQ

**Comment by Undertakergabo** [comment]
https://us.docs.wps.com/l/sAEnpbAK9p5ubAZrWkfarpxQ

**Comment by PowerVANO** [comment]
@luisantoniocrag your work has been accepted by @Horusfeathers and the bounty has been paid.
