### ISSUE TITLE
Ambassador Task: Translate Horizen Website Content - Hindi

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#43]
**Scope of work:**

This task is to translate the following pages into Hindi

- https://www.horizen.io/
- https://www.horizen.io/sidechain/
- https://www.horizen.io/node-hosting/

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within two weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $10 per page completed, $30 in total (Paid in ZEN)**

**Comment by soham117** [comment]
Kindly assign this task to me, sir. I know Hindi and English

**Comment by PowerVANO** [comment]
Hi @soham117 
Please apply for our Ambassador program first: https://www.horizen.io/ambassadors/

**Comment by BRAZENIUM** [comment]
Hello sir, I have already applied for the ambassador. And as I'm fluent in Hindi I can help in translating the task. I am keen Interested in this task.
