### ISSUE TITLE
Ambassador Task: Translate the Zendoo Whitepaper - Hindi

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#44]
**Scope of work:**

- Translate the full Zendoo whitepaper in Italian: https://www.horizen.io/assets/files/Horizen-Sidechain-Zendoo-A_zk-SNARK-Verifiable-Cross-Chain-Transfer-Protocol.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by soham117** [comment]
Can I get this task? I know Hindi and English very well

**Comment by PowerVANO** [comment]
Hi @soham117 
Yes, you can, but you have to be approved in our Horizen Ambassadors program first. Please apply here: https://www.horizen.io/ambassadors/

**Comment by TINYPHYNIX** [comment]
I'm interested in this task

**Comment by GaloisField2718** [comment]
Hi, is there a bounty to translate Whitepaper in french ?
