### ISSUE TITLE
Ambassador Task: Translate the Horizen Whitepaper - Hindi

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#45]
**Scope of work:**

- Translate the full Zendoo whitepaper in Hindi: https://www.horizen.io/assets/files/Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by soham117** [comment]
Sir , Can you please assign this task to me ?

**Comment by Wajahat8** [comment]
Sir , 
Can I join  for this task  ?

**Comment by Thanaphon1998** [comment]
Sir , Can you please assign this task to me ?

**Comment by PowerVANO** [comment]
Hi @soham117 @Wajahat8 @Thanaphon1998 
Are you Horizen Ambassadors already? If not, please apply and wait for the approval before starting to do this task: https://www.horizen.io/ambassadors/

**Comment by soham117** [comment]
@PowerVANO I know about the ambassador program. I haven't applied yet as I was a little busy. I'll fill the from soon ! Thank you

**Comment by BRAZENIUM** [comment]
I am keen Interested in this task. I have already applied for the ambassador. Sir, kindly assign this to me.
