### ISSUE TITLE
Ambassador Task: Translate the Horizen Whitepaper - Italian

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#46]
**Scope of work:**

- Translate the full Zendoo whitepaper in Italian: https://www.horizen.io/assets/files/Horizen-Sidechains-Decoupled-Consensus-Between-Chains.pdf

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador. The task must be completed within 4 weeks of accepting it. The person who accepts this task must provide a status update once a week. If the person who accepts this task does not complete the schedule milestones listed above the task will be reopened.

**Budget: $200 (Paid in ZEN)**

**Comment by Dutch71086** [comment]
I'll do this task

**Comment by Dannyednut** [comment]
I'm in for this task

**Comment by PowerVANO** [comment]
Hi @Dannyednut @Dutch71086
Are you Horizen Ambassadors already? If not, please apply first and wait for the approval before starting this task: https://www.horizen.io/ambassadors/

**Comment by Zeus-5** [comment]
Hi, I believe i can help pull this off... All i ask is a chance

**Comment by MarioCr99** [comment]
I will do the task

**Comment by Jasondolino** [comment]
I will take this task

**Comment by Dannyednut** [comment]
I accepted this task and im already working in it
