### ISSUE TITLE
Bug Transaction "Pending" Sphere By Horizen Testnet

### ISSUE THREAD

**Issue by agus311** [HorizenOfficial/HDE-Proposals#54]
Recap of Testing Results for Cobalt and Sphere Wallets by Horizen Tesnet.

I followed TokenMint Launch Phase1 (https://blog.horizen.io/tokenmint-alpha-1-testnet-launch/) and created my Cobalt wallet and created my wallet address (d60466f763cefe21a059e6cb67887b81fe53efd9e88eee4b05c243b903603c3f).

I downloaded the Sphere By Horizen test Wallet via this link (https://blog.horizen.io/tutorial-sending-tzen-to-cobalt/). And then create a new wallet and create a wallet address (ztiQRGGv5q6WgsPZGeFkh922GUmPgnLQ4Cf). And then go to the Heap site (https://heap.horizen.io/) to claim the free ZEN testnet.

My discord username agus_9830#8994

I made a forward transfer from my Horizen test wallet to my cobalt wallet via a sidechain process. see TXID(https://explorer-testnet.horizen.io/tx/a8c4ca50b56de01d1dc35242209cf0e2bc1e008f5438567db4083f2f10895840).

I transferred 1TZNY to e259c170f497cb266021d91b7eca983bf5bb32e8125c1fe2a76ed277021592d2 from my Cobalt wallet. See TXID (https://explorer-testnet.tokenmint.global/tx/c8ad54fa3a16763f6bd63f056a441b79f0ebad4648d802f3c3a1f54058d0a6a1).

I Send 1tZEN from my Cobalt wallet to my Horizen testnet wallet. See TXID (https://explorer-testnet.tokenmint.global/tx/a7cbdc0f44f757064e1295bf14b4906de7057e16672757eab7e5caa18f691e1e).

My take on UI/UX and etc:

I found an error on Sphere from net test horizon, when I send tZen to cobalt wallet, in transaction view there is no information that tZen was sent and there is only pending information. For the second, I hope that the settings feature on the Cobalt wallet will add some security features such as 2FA and fingerprints. and for the third there is no confirmation on the coblat wallet when making this transaction making users confused whether the token lands safely or not?...
![C](https://user-images.githubusercontent.com/105117649/167259378-2a22f4df-7752-4971-a2f3-79ef1335cc97.PNG)
![B](https://user-images.githubusercontent.com/105117649/167259381-2c487e63-fff0-4706-9fa4-1b91a72ec6a5.PNG)
![A](https://user-images.githubusercontent.com/105117649/167259382-6f60585e-913b-4d77-ad8c-7a7425aad045.PNG)
![E](https://user-images.githubusercontent.com/105117649/167259384-a1b083b9-991a-4fc3-9730-f6b6d475ee98.PNG)
![D](https://user-images.githubusercontent.com/105117649/167259385-85feb9fa-25aa-41be-a758-6a3277b62119.PNG)

**Comment by iantheitguy** [comment]
Transfer 1 TZNY from Cobalt wallet to this address: crash the software cant access my wallet e259c170f497cb266021d91b7eca983bf5bb32e8125c1fe2a76ed277021592d2 feel like the app crash no sign of the TZNY was send . It say success but did not show tokens gone click back and. It just say send Pending. app crash cant access the wallet address. How do i fix the problem reinstall?

https://github.com/HorizenOfficial/HDE-Proposals/issues/51#issuecomment-1119844626

Hope to hear what to do next
[horizen test ian notes.docx](https://github.com/HorizenOfficial/HDE-Proposals/files/8642597/horizen.test.ian.notes.docx)
https://explorer-testnet.tokenmint.global/tx/0db468a0d6964369f49d4985e09362edcf827b671fc2f5c1ea493b3dd2eac43e my last transaction
https://explorer-testnet.tokenmint.global/address/eb47f454d6657aa6e6ce942877bfd5e149fe7f0cd988771764fa5c15503ac53a

would it fix the problem after the transaction goes through?

Zen wallet for bounty reward: znU6fLM2aaHAeG7uxamzVFgAkDcyxUJaRj9

Discord name: iantheitguy#7210

error from the wallet

.Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown. main.js:1

more infor https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

.Content Security Policy of your site blocks the use of 'eval' in JavaScript`

The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.

main.js:2 script-src blocked
