### ISSUE TITLE
Ambassador Task: Create a video about your experience creating a token on TokenMint on testnet

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#66]
**Scope of work:**

This video should be no longer than 5 minutes but must cover:
- What is TokenMint	
- How to get test TZEN
- How to get Testnet Sphere wallet and Testnet Cobalt wallet
- Where to find documentation and resources
- The steps required to create a token

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador or pre-approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval.

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide bi-weekly updates during the period they are working on the task.

**Budget: $50 in ZEN per person / Total of $300 (up to 6 participants)

**Comment by DeFiMoney-Printer** [comment]
@PowerVANO I'd like to take this task

**Comment by DeFiMoney-Printer** [comment]
> @PowerVANO I'd like to take this task

Note: I may take up the written task first, and use it to guide the video for this task. stay tuned :)

**Comment by PowerVANO** [comment]
More entries won't be accepted for this task. Please jump to the mainnet task: https://github.com/HorizenOfficial/HDE-Proposals/issues/67

@DeFiMoney-Printer please let us know if you have already started doing this or the written task. If not, it would be best for you to jump the mainnet task above as well.

**Comment by PowerVANO** [comment]
Closing this one as [DeFiMoney-Printer](https://github.com/DeFiMoney-Printer) has done the mainnet task.
