### ISSUE TITLE
Ambassador Task: Translate the TokenMint Platform User Guide - French

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#68]
**Scope of work:**

- Translate the full TokenMint platform [user guide](https://docs.google.com/document/d/1SFU6XVd4Ex9alKzRThGIgmJvq-gCWMgy/edit?usp=sharing&ouid=100421764537297846576&rtpof=true&sd=true) in French

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador or pre-approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval.

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide twice a week updates during the period they are working on the task. Once accepted, the task should be completed in 2 weeks time.

**Budget: $100 in ZEN**

**Comment by xgarreau** [comment]
Hi ! I would like to take this task.

**Comment by xgarreau** [comment]
> Hi ! I would like to take this task.

Starting page 31/57 ^^

**Comment by PowerVANO** [comment]
@horusfeathers FYI ^^

**Comment by xgarreau** [comment]
Hi ! 
Here is a French user guide :)
--> https://docs.google.com/document/d/16C-UAGrQhJd5VltNLcJC8enxleKtsF6p
Let me know if there is something to improve.
Have a nice day !
Xavier

**Comment by Horusfeathers** [comment]
> https://docs.google.com/document/d/16C-UAGrQhJd5VltNLcJC8enxleKtsF6p

Thank you @xgarreau please submit your claim form. 

@PowerVANO please close out the task

**Comment by PowerVANO** [comment]
Payment processing for this one as well.

**Comment by PowerVANO** [comment]
This task has been paid. Thank you for your work @xgarreau!
