### ISSUE TITLE
Ambassador Task: Translate the TokenMint Platform User Guide - Spanish

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#69]
**Scope of work:**

- Translate the full TokenMint platform [user guide](https://docs.google.com/document/d/1SFU6XVd4Ex9alKzRThGIgmJvq-gCWMgy/edit?usp=sharing&ouid=100421764537297846576&rtpof=true&sd=true) in Spanish

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador or pre-approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval.

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide twice a week updates during the period they are working on the task. Once accepted, the task should be completed in 2 weeks time.

**Budget: $100 in ZEN**

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO Could I take this task please?

**Comment by Horusfeathers** [comment]
> Hi @PowerVANO @Horusfeathers Could I take this task please?

Absolutely!

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO @Horusfeathers 

The Spanish Translation of TokenMint Platform User Guide is done:

https://docs.google.com/document/d/1FpuSO3VdSoK1QhEzvh_PqBw4vi2CuLo4VdhcEvuzu1g/edit?usp=sharing

**Comment by luisantoniocrag** [comment]
@PowerVANO @Horusfeathers Could I take another task while you review this one please?

**Comment by PowerVANO** [comment]
@luisantoniocrag of course! You can take multiple tasks at the same time.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag please submit a bounty claim request form from the HDE website.

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO Thank you! 

I tried to authenticate myself in HDE platform but it seems there is an error when try to login with GitHub. I tried several times and from many browsers.

<img width="1512" alt="Screenshot 2022-11-25 at 19 41 10" src="https://user-images.githubusercontent.com/42625753/204067618-978fe3e6-78ef-4d03-9e33-052bfb490e2a.png">

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 

Thanks for reporting the issue. Can you please try again? It seems the issue has been fixed on our end and login with GH works again.

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO 

I tried but I got same error: 
`error: 504 Gateway time-out`

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag

Let's do it over email - I have just sent a message to you again. We need to confirm that your details have not been changed.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag Bounty has been paid.

**Comment by luisantoniocrag** [comment]
Received! thank you!
