### ISSUE TITLE
Ambassador Task: Translate the TokenMint Platform User Guide - Russian

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/HDE-Proposals#72]
**Scope of work:**

- Translate the full TokenMint platform [user guide](https://docs.google.com/document/d/1SFU6XVd4Ex9alKzRThGIgmJvq-gCWMgy/edit?usp=sharing&ouid=100421764537297846576&rtpof=true&sd=true) in Russian

**Schedule Milestones:**

This task may only be completed by an official Horizen Ambassador or pre-approved person. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the article before approval.

If you are not an ambassador and would like to be approved for this task, contact erica [at] horizen.io

Ambassadors that accept this task must provide twice a week updates during the period they are working on the task. Once accepted, the task should be completed in 2 weeks time.

**Budget: $100 in ZEN**

**Comment by coder-zafarjon** [comment]
Hello! I will be help you for translating to russian...
